name: Deploy RAP
on:
  # release:
  #   types: [published]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        shell: bash
      - name: Build
        run: npm run build
        shell: bash
      - name: Deploy
        uses: bitovi/github-actions-react-to-github-pages@v1.2.1